# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: 
  contents: write


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v4.0.0
      with:
          # Artifact name
          name: github-pages # optional, default is github-pages
        # Path of the directory containing the static assets.
          path: 'dist/'  # default is _site/
          
    - name: GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865
      uses: crazy-max/ghaction-github-pages@v4.2.0
      with:
          build_dir: './dist'
          target_branch: 'gh-web'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

          
          

